Repository rapidsai/docs, pull requests merged in 2019-05, with the labels that each got.

#8 [DOC] Added description of get_rapids_dataset_root_dir() and how both devel…
  maintainers/datasets.md
  maintainers/testing.md
Labels: 4 - Needs Reviewer, doc, gpuCI

#10 [REVIEW] Add gpuCI docs
  maintainers/gpuci.md
  maintainers/testing.md
Labels: 3 - Ready for Review, doc, gpuCI

#17 [REVIEW] Update API/library paths for 0.7 release
  .gitignore
  _data/apis.yml
  _data/libs.yml
  api/cudf/0.6.md
  api/cugraph/0.6.md
  api/cuml/0.6.md
  api/libcudf/0.6.md
  api/nvstrings/0.3.md
  api/rmm/0.6.md
Labels: 3 - Ready for Review

#22 [REVIEW] Formatting & remove pip mention
  maintainers/gpuci.md
Labels: 3 - Ready for Review
