Repository rapidsai/docs, pull requests merged in 2019-10, with the labels that each got.

#45 [REVIEW] Document gpuCI environment variables
  maintainers/gpuci.md
Labels: 3 - Ready for Review

#49 Updates for RAPIDS 0.10
  demos/containers/rapids-demo.md
Labels: ! - Release

#48 API docs update for v0.10 release
  _data/apis.yml
  _data/libs.yml
  _data/releases.yml
  api/cudf/0.9.md
  api/cugraph/0.9.md
  api/cuml/0.9.md
  api/libcudf/0.9.md
  api/libnvstrings/0.9.md
  api/nvstrings/0.9.md
  api/rmm/0.9.md
Labels: ! - Release, 3 - Ready for Review, doc

#51 Update v0.11 release dates
  maintainers/maintainers.md
  releases/schedule.md
Labels: doc
