Repository rapidsai/docs, pull requests merged in 2020-08, with the labels that each got.

#109 DOC Add RAPIDS release delay notice
  _layouts/notice-index.html
  _notices/rgn0003.md
  maintainers/maintainers.md
Labels: 3 - Ready for Review, doc

#115 DOC Update and add RAPIDS notices for v0.15 Release
  _notices/rdn0001.md
  _notices/rgn0001.md
  _notices/rgn0002.md
  _notices/rgn0003.md
  _notices/rgn0004.md
  _notices/rsn0001.md
  _notices/rsn0002.md
  _notices/rsn0003.md
  _notices/rsn0004.md
  notices/feed.xml
  notices/notices.md
Labels: ! - Release, 5 - Ready to Merge, doc

#114 [REVIEW] - Update docs for 0.15 release
  _data/docs.yml
  _data/releases.yml
  _data/versions.yml
  assets/css/just-the-docs.css
  demos/rapids-demo.md
  maintainers/gpuci.md
  maintainers/maintainers.md
  releases/schedule.md
Labels: ! - Release, 5 - Ready to Merge
